[project]
name = "genai-google"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cogdb>=3.0.7",
    "langchain-google-genai>=2.1.2",
    "ollama>=0.4.7",
]
